import { NextApiRequest, NextApiResponse } from 'next'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { generateArenaPrompt, generateArenaQuizSet } from '@/lib/ai'

// Founder builds Arena games from the structured rule-engine template.
// `config` holds the flexible JSON: mechanics/attempt_rules/rewards/anti_cheat/ranking.
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const session = await getServerSession(req, res, authOptions)
  if (!session || session.user.role !== 'FOUNDER') return res.status(403).json({ error: 'Forbidden' })

  if (req.method === 'GET') {
    const challenges = await prisma.arenaChallenge.findMany({
      orderBy: { createdAt: 'desc' },
      include: { _count: { select: { entries: true } } },
    })
    return res.json({ challenges })
  }

  if (req.method === 'POST') {
    const {
      title, description, category, icon, type,
      xpReward, cashReward, endsAt, isDaily, config,
    } = req.body

    if (!title || !endsAt) return res.status(400).json({ error: 'Title and end date required' })
    if (!config?.mechanics?.type) return res.status(400).json({ error: 'Game mechanics type required' })

    // The objective/description is the ONLY spec players ever see, and the only
    // context the AI validator has to grade against. It used to be optional in
    // practice (the "*" in the founder form wasn't enforced here), which let
    // effectively-blank games go live with no instructions and ungradable entries.
    // Now: either the Founder supplies one, or we auto-generate one so a game can
    // never deploy with nothing for players to go on.
    let resolvedObjective: string = (description || config?.objective || '').trim()
    let autoGenerated = false

    // puzzle_type only makes sense for the free-text mechanics (Logic's
    // "puzzle" type, Creative) — quiz questions come from generateArenaQuizSet
    // instead, and typing/social_task/tap_speed don't have a "puzzle style".
    const puzzleType: string | undefined = config?.mechanics?.puzzle_type

    if (!resolvedObjective) {
      const generated = await generateArenaPrompt(
        category || 'Logic',
        config?.difficulty || 'medium',
        puzzleType
      )
      resolvedObjective = generated.prompt
      autoGenerated = true
    }

    // "Quiz" games get a real N-question round instead of a free-text box
    // the AI validator has to guess-grade — and instead of the single
    // question it used to be, which barely counted as a "game". correctIndex
    // for every question lives only in this server-side config —
    // pages/api/arena.ts strips it before anything reaches the client, and
    // submit.ts is the only place that reads it back out to grade an attempt.
    // question_count / difficulty_curve are Founder-configurable (see the
    // Arena creation form) — generateArenaQuizSet clamps count to 3-15.
    let quizQuestions: Awaited<ReturnType<typeof generateArenaQuizSet>> | undefined
    if (config?.mechanics?.type === 'quiz') {
      quizQuestions = await generateArenaQuizSet(
        category || 'Logic',
        config?.difficulty || 'medium',
        config?.mechanics?.question_count || 5,
        !!config?.mechanics?.difficulty_curve
      )
    }

    const resolvedConfig = {
      ...config,
      objective: resolvedObjective,
      objective_auto_generated: autoGenerated,
      ...(quizQuestions ? { quiz: { questions: quizQuestions } } : {}),
    }

    if (isDaily) {
      // Only one daily challenge active at a time — demote any existing one.
      await prisma.arenaChallenge.updateMany({
        where: { isDaily: true, status: 'ACTIVE' },
        data: { isDaily: false },
      })
    }

    const challenge = await prisma.arenaChallenge.create({
      data: {
        title,
        description: resolvedObjective,
        type: type || config?.mechanics?.type || 'CREATIVE_PROMPT',
        category: category || 'Logic',
        icon: icon || '◆',
        xpReward: parseInt(xpReward) || config?.rewards?.xp || 50,
        cashReward: cashReward ? parseFloat(cashReward) : null,
        endsAt: new Date(endsAt),
        isDaily: !!isDaily,
        status: 'ACTIVE',
        config: resolvedConfig,
      },
    })
    return res.json({ challenge, autoGenerated })
  }

  if (req.method === 'PATCH') {
    const { id, status, isDaily } = req.body
    if (!id) return res.status(400).json({ error: 'id required' })

    if (isDaily) {
      await prisma.arenaChallenge.updateMany({
        where: { isDaily: true, status: 'ACTIVE', NOT: { id } },
        data: { isDaily: false },
      })
    }

    const challenge = await prisma.arenaChallenge.update({
      where: { id },
      data: {
        ...(status ? { status } : {}),
        ...(typeof isDaily === 'boolean' ? { isDaily } : {}),
      },
    })
    return res.json({ challenge })
  }

  if (req.method === 'DELETE') {
    const { id } = req.body
    if (!id) return res.status(400).json({ error: 'id required' })
    try {
      // ArenaEntry.challenge has no cascade delete configured, so deleting
      // a challenge that already has entries (every deployed test game
      // does) previously threw an unhandled foreign-key constraint error
      // here — a bare 500 with no message, and the frontend didn't check
      // res.ok, so the button looked like it silently did nothing. Delete
      // dependents first, in a transaction, so either both go or neither do.
      await prisma.$transaction([
        prisma.arenaEntry.deleteMany({ where: { challengeId: id } }),
        prisma.arenaChallenge.delete({ where: { id } }),
      ])
      return res.json({ ok: true })
    } catch (err: any) {
      console.error('[founder/arena] delete failed:', err)
      return res.status(500).json({ error: err?.message || 'Failed to delete game' })
    }
  }

  res.status(405).end()
}