import { NextApiRequest, NextApiResponse } from 'next'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { generateArenaPrompt, generateArenaQuiz } from '@/lib/ai'

// Founder builds Arena games from the structured rule-engine template.
// `config` holds the flexible JSON: mechanics/attempt_rules/rewards/anti_cheat/ranking.
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const session = await getServerSession(req, res, authOptions)
  if (!session || session.user.role !== 'FOUNDER') return res.status(403).json({ error: 'Forbidden' })

  if (req.method === 'GET') {
    const challenges = await prisma.arenaChallenge.findMany({
      orderBy: { createdAt: 'desc' },
      include: { _count: { select: { entries: true } } },
    })
    return res.json({ challenges })
  }

  if (req.method === 'POST') {
    const {
      title, description, category, icon, type,
      xpReward, cashReward, endsAt, isDaily, config,
    } = req.body

    if (!title || !endsAt) return res.status(400).json({ error: 'Title and end date required' })
    if (!config?.mechanics?.type) return res.status(400).json({ error: 'Game mechanics type required' })

    // The objective/description is the ONLY spec players ever see, and the only
    // context the AI validator has to grade against. It used to be optional in
    // practice (the "*" in the founder form wasn't enforced here), which let
    // effectively-blank games go live with no instructions and ungradable entries.
    // Now: either the Founder supplies one, or we auto-generate one so a game can
    // never deploy with nothing for players to go on.
    let resolvedObjective: string = (description || config?.objective || '').trim()
    let autoGenerated = false

    if (!resolvedObjective) {
      const generated = await generateArenaPrompt(
        category || 'Logic',
        config?.difficulty || 'medium'
      )
      resolvedObjective = generated.prompt
      autoGenerated = true
    }

    // "Quiz" games get a real structured multiple-choice question instead of
    // a free-text box the AI validator has to guess-grade. correctIndex lives
    // only in this server-side config — pages/api/arena.ts and start.ts strip
    // it before anything reaches the client, and submit.ts is the only place
    // that reads it back out to grade an attempt.
    let quiz: { question: string; options: string[]; correctIndex: number; explanation?: string } | undefined
    if (config?.mechanics?.type === 'quiz') {
      quiz = await generateArenaQuiz(category || 'Logic', config?.difficulty || 'medium')
    }

    const resolvedConfig = {
      ...config,
      objective: resolvedObjective,
      objective_auto_generated: autoGenerated,
      ...(quiz ? { quiz } : {}),
    }

    if (isDaily) {
      // Only one daily challenge active at a time — demote any existing one.
      await prisma.arenaChallenge.updateMany({
        where: { isDaily: true, status: 'ACTIVE' },
        data: { isDaily: false },
      })
    }

    const challenge = await prisma.arenaChallenge.create({
      data: {
        title,
        description: resolvedObjective,
        type: type || config?.mechanics?.type || 'CREATIVE_PROMPT',
        category: category || 'Logic',
        icon: icon || '◆',
        xpReward: parseInt(xpReward) || config?.rewards?.xp || 50,
        cashReward: cashReward ? parseFloat(cashReward) : null,
        endsAt: new Date(endsAt),
        isDaily: !!isDaily,
        status: 'ACTIVE',
        config: resolvedConfig,
      },
    })
    return res.json({ challenge, autoGenerated })
  }

  if (req.method === 'PATCH') {
    const { id, status, isDaily } = req.body
    if (!id) return res.status(400).json({ error: 'id required' })

    if (isDaily) {
      await prisma.arenaChallenge.updateMany({
        where: { isDaily: true, status: 'ACTIVE', NOT: { id } },
        data: { isDaily: false },
      })
    }

    const challenge = await prisma.arenaChallenge.update({
      where: { id },
      data: {
        ...(status ? { status } : {}),
        ...(typeof isDaily === 'boolean' ? { isDaily } : {}),
      },
    })
    return res.json({ challenge })
  }

  if (req.method === 'DELETE') {
    const { id } = req.body
    await prisma.arenaChallenge.delete({ where: { id } })
    return res.json({ ok: true })
  }

  res.status(405).end()
}